name: Build and Test
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build & Test
        run: yarn build && yarn test
